name = "lean-shake"
version = "0.1.0"
defaultTargets = ["Shake"]
testDriver = "ShakeTestsExe"
lintDriver = "batteries/runLinter"

[leanOptions]
weak.linter.mathlibStandardSet = true
weak.linter.flexible = true
weak.linter.pythonStyle = false
weak.linter.checkInitImports = false
weak.linter.allScriptsDocumented = false
weak.linter.unicodeLinter = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "Shake"
globs = ["Shake.*"]

[[lean_exe]]
name = "ShakeTestsExe"
root = "ShakeTests"
supportInterpreter = true

[[lean_exe]]
name = "lshake"
root = "Main"
supportInterpreter = true
